import { add } from "lodash";

let contact = () => {
  let content = document.querySelector(".content");
  let h1 = document.createElement("h1");
  h1.innerHTML = "Contact Form";
  content.appendChild(h1);
  content.style.height = "80vh";
  // content.style.width = "100%";
  content.style.backgroundColor = "skyblue";
  let box = document.createElement("div");
  box.style.height = "350px";
  box.style.width = "500px";
  box.style.fontWeight = "bold";
  box.style.border = "2px solid black";
  content.style.display = "flex";
  content.style.flexDirection = "column";
  content.style.justifyContent = "center";
  content.style.alignItems = "center";
  let boxdiv1 = document.createElement("div");
  boxdiv1.style.display = "flex";
  boxdiv1.style.alignItems = "center";
  let boxdiv1text = document.createElement("div");
  boxdiv1text.innerHTML = "NAME";
  let boxdiv1input = document.createElement("div");
  let name = document.createElement("input");
  boxdiv1.style.margin = "15px";
  name.style.width = "400px";
  name.style.borderRadius = "7px";
  name.style.padding = "8px";

  boxdiv1input.appendChild(name);
  boxdiv1.appendChild(boxdiv1text);
  boxdiv1.appendChild(boxdiv1input);
  box.appendChild(boxdiv1);
  let boxdiv2 = document.createElement("div");
  boxdiv2.style.display = "flex";
  boxdiv2.style.alignItems = "center";
  let boxdiv2text = document.createElement("div");
  boxdiv2text.innerHTML = "EMAIL";
  let boxdiv2input = document.createElement("div");
  let email = document.createElement("input");
  boxdiv2.style.margin = "10px";
  email.style.width = "400px";
  email.style.borderRadius = "7px";
  email.style.padding = "8px";
  email.type = "email";
  boxdiv2input.appendChild(email);
  boxdiv2.appendChild(boxdiv2text);
  boxdiv2.appendChild(boxdiv2input);
  box.appendChild(boxdiv2);
  let boxdiv3 = document.createElement("div");
  boxdiv3.style.display = "flex";
  boxdiv3.style.alignItems = "center";
  let boxdiv3text = document.createElement("div");
  boxdiv3text.innerHTML = "PHONE";
  let boxdiv3input = document.createElement("div");
  let phone = document.createElement("input");
  boxdiv3.style.margin = "10px";
  phone.style.width = "400px";
  phone.style.borderRadius = "7px";
  phone.style.padding = "8px";
  phone.type = "tel";
  boxdiv3input.appendChild(phone);
  boxdiv3.appendChild(boxdiv3text);
  boxdiv3.appendChild(boxdiv3input);
  box.appendChild(boxdiv3);
  let boxdiv5 = document.createElement("div");
  boxdiv5.style.display = "flex";
  boxdiv5.style.alignItems = "center";
  let boxdiv5text = document.createElement("div");
  boxdiv5text.innerHTML = "ADDRE";
  let boxdiv5input = document.createElement("div");
  let address = document.createElement("textarea");
  boxdiv5.style.margin = "10px";
  address.style.width = "405px";
  address.style.height = "100px";
  address.style.borderRadius = "7px";
  address.style.padding = "8px";
  boxdiv5input.appendChild(address);
  boxdiv5.appendChild(boxdiv5text);
  boxdiv5.appendChild(boxdiv5input);
  box.appendChild(boxdiv5);
  let btn = document.createElement("button");
  btn.style.marginLeft = "55px";
  btn.style.backgroundColor = "green";
  btn.type = "submit";
  btn.innerHTML = "Submit";
  btn.style.width = "120px";
  box.appendChild(btn);

  content.appendChild(box);
};
export { contact };
